version: "2.1"

services:
  credentials:
    volumes:
      - credentials-sync:/edx/app/credentials/credentials:nocopy
  discovery:
    volumes:
      - discovery-sync:/edx/app/discovery/discovery:nocopy
  ecommerce:
    volumes:
      - ecommerce-sync:/edx/app/ecommerce/ecommerce:nocopy
  lms:
    volumes:
      - edxapp-sync:/edx/app/edxapp/edx-platform:nocopy
  studio:
    volumes:
      - edxapp-sync:/edx/app/edxapp/edx-platform:nocopy
  forum:
    volumes:
      - forum-sync:/edx/app/forum/cs_comments_service:nocopy
  registrar:
    volumes:
      - registrar-sync:/edx/app/registrar/registrar:nocopy
  gradebook:
    volumes:
      - gradebook-sync:/edx/app/gradebook/gradebook:nocopy
  program-console:
    volumes:
      - program-console-sync:/edx/app/program-console:nocopy
  wordpress:
    volumes:
      - wordpress-sync:/var/www/html/wp-content/plugins/edly-wp-plugin:nocopy
      - wordpress-sync:/var/www/html/wp-content/themes/edly-wp-theme:nocopy
  panel_frontend:
    volumes:
      - panel_frontend-sync:/var/www/html/edly-panel-frontend:cached

volumes:
  credentials-sync:
    external: true
  discovery-sync:
    external: true
  ecommerce-sync:
    external: true
  edxapp-sync:
    external: true
  forum-sync:
    external: true
  registrar-sync:
    external: true
  gradebook-sync:
    external: true
  program-console-sync:
  wordpress-sync:
    external: true
  panel_frontend-sync:
    external: true
